### ISSUE TITLE
Missing products

### ISSUE THREAD

**Issue by DavidT01** [JJCUBER/HayDayImageGeneratorSite#12]
Hello, you are missing following products:

lobster salad
lemon essential oil
mint essential oil

**Comment by JJCUBER** [comment]
Ah it looks like we already discussed this in discord so I'll close the issue.

(Just for documentation purposes, the lobster salad was actually called "seafood salad" [which is in the list], and at the time, the essential oils were addable but not yet in the list of autocompletion names due to them being new.  It seems that they are now in the list of names since the HayDay wiki updated the proper pages.)
